// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "eleven1.h"

/////////////////////////////////////////////////////////////////////////////
// CEleven

IMPLEMENT_DYNCREATE(CEleven, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CEleven properties

/////////////////////////////////////////////////////////////////////////////
// CEleven operations

void CEleven::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
